#!/usr/bin/env python
# encoding: utf-8

def build(ctx):
	ctx.program(source='pwmanage.c', 
			target='pwmanage', 
			includes='..',
			lib=['tdb', 'talloc', 'crypt'],
			cflags = ['-g', '-Wall'],
			install_path = '${PREFIX}/bin'
			)
